import React, {useEffect, useRef, useState} from 'react';
import { Search, Bell, Wifi, WifiOff, ChevronDown, LogOut, RefreshCw, Users, AlertTriangle, CheckCircle2 } from 'lucide-react';
import apiClient from '../../api/client';
export default function TopNavbar({activeSectionTitle,onToggleSidebar,onOpenAuthModal}) {
 const [online,setOnline]=useState(null); const [user,setUser]=useState(null); const [open,setOpen]=useState(false); const [notificationsOpen,setNotificationsOpen]=useState(false); const [pending,setPending]=useState(0); const notificationsRef=useRef(null);
 const check=async()=>{try{await apiClient.get('/health');setOnline(true)}catch{setOnline(false)}};
 useEffect(()=>{check(); try{setUser(JSON.parse(localStorage.getItem('oceanflow_admin_user')||'null'));setPending(Number(localStorage.getItem('oceanflow-offline-pending')||0))}catch{} const id=setInterval(check,30000); return()=>clearInterval(id)},[]);
 useEffect(()=>{const closeOnOutside=(event)=>{if(notificationsRef.current&&!notificationsRef.current.contains(event.target))setNotificationsOpen(false)}; document.addEventListener('mousedown',closeOnOutside); return()=>document.removeEventListener('mousedown',closeOnOutside)},[]);
 const logout=()=>{localStorage.removeItem('oceanflow_admin_token');localStorage.removeItem('oceanflow_admin_user');setUser(null);setOpen(false)};
	return <header className="of-topbar"><div className="of-breadcrumb"><button className="of-mobile-menu" onClick={onToggleSidebar}>☰</button><span>OceanFlow</span><b>/</b><strong>{activeSectionTitle}</strong></div><div className="of-top-actions"><label className="of-search"><Search size={16}/><input placeholder="Tìm kiếm dữ liệu..." aria-label="Tìm kiếm"/></label><button className="of-icon-btn" title="Làm mới trạng thái" onClick={check}><RefreshCw size={17}/></button><span className={`of-connect ${online===true?'online':online===false?'offline':''}`}>{online===true?<Wifi size={15}/>:online===false?<WifiOff size={15}/>:<span className="spinner"/>}{online===true?'Đang kết nối':online===false?'Offline':'Đang kiểm tra'}</span>{pending>0&&<span className="of-sync-count">{pending} chờ Sync</span>}<div className="of-notification-wrap" ref={notificationsRef}><button className="of-icon-btn" title="Thông báo" aria-label="Mở thông báo" aria-expanded={notificationsOpen} onClick={()=>setNotificationsOpen(!notificationsOpen)}><Bell size={17}/><i/></button>{notificationsOpen&&<div className="of-notification-dropdown bg-[#1E293B] border border-slate-700 shadow-xl z-50" role="dialog" aria-label="Thông báo hệ thống"><div className="of-notification-head"><div><strong>Thông báo hệ thống</strong><small>Cập nhật vận hành gần đây</small></div><button className="of-notification-dismiss" onClick={()=>setNotificationsOpen(false)} aria-label="Đóng thông báo">×</button></div><div className="of-notification-list"><div className="of-notification-item"><CheckCircle2 size={17}/><div><strong>{online===true?'Backend đang kết nối':'Đang kiểm tra kết nối backend'}</strong><span>{online===true?'Dữ liệu trực tiếp sẵn sàng.':'Trạng thái sẽ được cập nhật tự động.'}</span></div></div>{pending>0?<div className="of-notification-item warning"><AlertTriangle size={17}/><div><strong>{pending} thao tác chờ đồng bộ</strong><span>Kiểm tra hàng đợi đồng bộ trước khi kết thúc ca.</span></div></div>:<div className="of-notification-item"><CheckCircle2 size={17}/><div><strong>Không có cảnh báo mới</strong><span>Hệ thống chưa ghi nhận cảnh báo bổ sung.</span></div></div>}</div></div>}</div><a className="of-portal-link" href="/"><Users size={14}/> Cổng hành khách</a><div className="of-user-wrap"><button className="of-user" onClick={()=>setOpen(!open)}><span>{user?.username?.[0]?.toUpperCase()||'O'}</span><em>{user?.username||'Nhân viên vận hành'}</em><ChevronDown size={15}/></button>{open&&<div className="of-user-menu">{user?<><small>Đang đăng nhập</small><b>{user.username}</b><button onClick={logout}><LogOut size={15}/>Đăng xuất</button></>:<button onClick={onOpenAuthModal}>Đăng nhập hệ thống</button>}</div>}</div></div></header>
}
