import React, { useEffect, useState } from 'react';
import { CalendarDays, Loader2, RefreshCw } from 'lucide-react';
import apiClient from '../../api/client';
import './PassengerBooking.css';

const date = (value) => value ? new Date(value).toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' }) : 'Đang cập nhật';
const statusText = { confirmed: 'Đã xác nhận', cancelled: 'Đã hủy', completed: 'Đã hoàn tất' };

export default function MyBookings({ passenger, tours }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await apiClient.get('/api/v1/bookings'); const bookings = Array.isArray(response.data) ? response.data : []; setItems(passenger?.id ? bookings.filter((booking) => Number(booking.passenger_id) === Number(passenger.id)) : []); } catch (requestError) { setError(requestError.response?.data?.error || requestError.message || 'Không thể tải booking.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [passenger?.id]);
  return <section className="pw-booking-view"><div className="pw-section-heading"><div><span className="pw-eyebrow">HÀNH TRÌNH CỦA BẠN</span><h1>Booking của tôi</h1></div><button className="pw-text-button" onClick={load}><RefreshCw size={16} /> Làm mới</button></div>{loading ? <div className="pw-booking-state"><Loader2 className="pw-spin" size={22} /> Đang tải booking...</div> : error ? <div className="pw-form-status error">{error}</div> : !passenger?.id ? <div className="pw-booking-state">Chưa xác định được hành khách hiện tại.</div> : items.length ? <div className="pw-booking-list">{items.map((booking) => { const tour = tours.find((item) => Number(item.id) === Number(booking.cruise_tour_id)); return <article className="pw-booking-row" key={booking.id}><div className="pw-booking-heading"><div><small>BOOKING REFERENCE</small><strong>{booking.reference || 'Đang cập nhật'}</strong></div><span className={`pw-status ${booking.status === 'cancelled' ? 'error' : booking.status === 'completed' ? 'success' : 'planned'}`}>{statusText[booking.status] || booking.status || 'Đang cập nhật'}</span></div><div className="pw-booking-details"><div><small>BOOKING ID</small><strong>#{booking.id}</strong></div><div><small>CRUISE / VOYAGE</small><strong>{tour?.name || `Chuyến #${booking.cruise_tour_id}`}</strong></div><div><small>SHIP</small><span>{tour?.ship || 'Tàu đang cập nhật'}</span></div><div><small>DEPARTURE DATE</small><span><CalendarDays size={14} /> {date(tour?.start_date)}</span></div><div><small>RETURN DATE</small><span><CalendarDays size={14} /> {date(tour?.end_date)}</span></div><div><small>PASSENGER ID</small><span>#{booking.passenger_id}</span></div><div><small>CABIN ID</small><span>{booking.cabin_id ?? 'Chưa gán'}</span></div><div><small>CRUISE TOUR ID</small><span>#{booking.cruise_tour_id}</span></div></div></article>; })}</div> : <div className="pw-booking-state"><h2>Chưa có booking</h2><p>Các chuyến đã đặt sẽ xuất hiện tại đây.</p></div>}</section>;
}