import React, { useEffect, useMemo, useState } from 'react';
import { Plus, Search, Users, X, CreditCard, BedDouble, WalletCards } from 'lucide-react';
import { passengersApi, bookingsApi } from '../api/cruiseApi';
import apiClient from '../api/client';
import EndpointStatusBanner from '../components/Common/EndpointStatusBanner';
import { PageHeader, LoadingState, ErrorState, EmptyState, StatusBadge } from '../components/Common/PageStates';

const statusMap = { booked: 'Đã đặt chỗ', embarked: 'Đã lên tàu', checked_in: 'Đã check-in', completed: 'Đã hoàn tất', cancelled: 'Đã hủy' };
export default function PassengersPage() {
  const [passengers, setPassengers] = useState([]); const [bookings, setBookings] = useState([]); const [isLive, setIsLive] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ first_name: '', last_name: '', cabin: '', status: 'booked' });
  const load = async () => { setLoading(true); setError(''); const [p, b] = await Promise.all([passengersApi.getAll(), bookingsApi.getAll()]); setPassengers(p.data || []); setBookings(b.data || []); setIsLive(Boolean(p.isLiveBackend)); if (p.error && b.error) setError('Không thể tải danh sách hành khách từ backend.'); setLoading(false); };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => passengers.filter((p) => !query.trim() || `${p.first_name} ${p.last_name} ${p.cabin || ''}`.toLowerCase().includes(query.toLowerCase())), [passengers, query]);
  const submit = async (e) => { e.preventDefault(); setSaving(true); try { const res = await apiClient.post('/api/v1/passengers', form); setPassengers((x) => [res.data, ...x]); setOpen(false); setForm({ first_name: '', last_name: '', cabin: '', status: 'booked' }); } catch (err) { setError(err.response?.data?.error || err.message); } finally { setSaving(false); } };
  return <div style={{ display: 'grid', gap: 16 }}>
    <PageHeader kicker="KHÁCH HÀNG" title="Hành khách" description="Quản lý danh sách hành khách và các liên kết quan trọng: Booking, Cabin, Tài khoản onboard, hoạt động và tour tham quan bờ." actions={<button className="of-primary" onClick={() => setOpen(true)}><Plus size={16} /> Thêm hành khách</button>} />
    <div className="of-flow"><span><Users size={14} /> Hành khách</span><span><CreditCard size={14} /> Booking</span><span><BedDouble size={14} /> Cabin</span><span><WalletCards size={14} /> Tài khoản onboard</span></div>
    <EndpointStatusBanner isLiveBackend={isLive} resourceName="Hành khách" />
    <div className="of-card of-card-pad"><label className="of-search" style={{ width: '100%' }}><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo tên hoặc cabin..." /></label></div>
    {loading && <LoadingState />}{!loading && error && <ErrorState message={error} onRetry={load} />}{!loading && !error && filtered.length === 0 && <EmptyState title="Chưa có hành khách" description="Dữ liệu hành khách sẽ xuất hiện sau khi được tạo từ quy trình Booking." action={<button className="of-primary" onClick={() => setOpen(true)}><Plus size={16} /> Thêm hành khách</button>} />}
    {!loading && filtered.length > 0 && <div className="of-card" style={{ overflow: 'hidden' }}><table className="of-table"><thead><tr><th>Hành khách</th><th>Cabin</th><th>Booking liên quan</th><th>Trạng thái</th></tr></thead><tbody>{filtered.map((p) => { const pb = bookings.filter((b) => b.passenger_id === p.id); return <tr key={p.id}><td><strong>{p.first_name} {p.last_name}</strong><div className="of-muted">Mã hành khách #{p.id}</div></td><td><span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><BedDouble size={14} />{p.cabin || 'Chưa gán cabin'}</span></td><td>{pb.length ? pb.map((b) => <span key={b.id} className="of-badge" style={{ marginRight: 5 }}>{b.reference}</span>) : <span className="of-muted">Chưa có booking</span>}</td><td><StatusBadge value={p.status} map={statusMap} /></td></tr>; })}</tbody></table></div>}
    {open && <div className="of-modal" onClick={() => setOpen(false)}><div className="of-modal-card" onClick={(e) => e.stopPropagation()}><div className="of-modal-head"><h2>Thêm hành khách</h2><button className="of-modal-close" onClick={() => setOpen(false)}><X size={16} /></button></div><form className="of-form" onSubmit={submit}><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}><label>Tên *<input value={form.first_name} onChange={(e) => setForm({ ...form, first_name: e.target.value })} required /></label><label>Họ *<input value={form.last_name} onChange={(e) => setForm({ ...form, last_name: e.target.value })} required /></label></div><label>Số cabin<input value={form.cabin} onChange={(e) => setForm({ ...form, cabin: e.target.value })} placeholder="Ví dụ: A-101" /></label><label>Trạng thái<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="booked">Đã đặt chỗ</option><option value="embarked">Đã lên tàu</option></select></label><div className="of-actions"><button type="button" className="of-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="of-primary" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu hành khách'}</button></div></form></div></div>}
  </div>;
}
