import React, { useEffect, useState } from 'react';
import { BarChart3, FileText, RefreshCw, WalletCards, CreditCard, Receipt } from 'lucide-react';
import apiClient from '../api/client';
import { PageHeader, LoadingState, ErrorState, EmptyState } from '../components/Common/PageStates';
import EndpointStatusBanner from '../components/Common/EndpointStatusBanner';
export default function ReportsPage(){
 const [summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await apiClient.get('/api/v1/operations/summary');setSummary(r.data)}catch(err){setError(err.response?.data?.error||err.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 return <div style={{display:'grid',gap:16}}><PageHeader kicker="TÀI CHÍNH" title="Báo cáo & đối soát" description="Tổng hợp số liệu vận hành và tài chính từ dữ liệu thực tế. Chỉ hiển thị khi backend có bản ghi tương ứng." actions={<button className="of-secondary" onClick={load}><RefreshCw size={15}/> Làm mới</button>}/><EndpointStatusBanner isLiveBackend={!!summary} resourceName="Báo cáo tổng hợp"/><div className="of-card of-card-pad"><div className="of-section-title">LUỒNG TÀI CHÍNH</div><div className="of-flow" style={{marginTop:12}}><span><Receipt size={14}/> Đơn dịch vụ</span><span><CreditCard size={14}/> POS transaction</span><span><WalletCards size={14}/> Onboard account</span><span>Đối soát</span><span>Settlement</span><span><FileText size={14}/> Invoice</span></div><p className="of-muted" style={{marginTop:10}}>Chi phí vận hành được quản lý riêng và không trộn lẫn với khoản charge của hành khách.</p></div>{loading&&<LoadingState/>}{!loading&&error&&<ErrorState message={error} onRetry={load}/>}{!loading&&!error&&!summary&&<EmptyState title="Chưa có dữ liệu báo cáo" description="Báo cáo sẽ xuất hiện khi hệ thống đã ghi nhận chuyến, hành khách, hoạt động và giao dịch."/>}{!loading&&!error&&summary&&<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:14}}><div className="of-card of-card-pad"><div className="of-section-title">VẬN HÀNH</div><div style={{marginTop:10,display:'grid',gap:8}}><Row label="Chuyến du thuyền" value={summary.tours}/><Row label="Hành khách" value={summary.passengers}/><Row label="Booking" value={summary.bookings}/><Row label="Lịch hoạt động" value={summary.schedules}/><Row label="Đăng ký hoạt động" value={summary.registrations}/><Row label="Check-in" value={summary.checkins}/></div></div><div className="of-card of-card-pad"><div className="of-section-title">DỊCH VỤ & BỜ</div><div style={{marginTop:10,display:'grid',gap:8}}><Row label="Tour tham quan bờ" value={summary.excursions}/><Row label="Đăng ký excursion" value={summary.excursion_registrations}/><Row label="Đơn dịch vụ" value={summary.service_orders}/><Row label="Giao dịch POS" value={summary.pos_transactions}/></div></div><div className="of-card of-card-pad"><div className="of-section-title">TÀI CHÍNH</div><div style={{marginTop:10,display:'grid',gap:8}}><Row label="Số dư onboard" value={`${summary.outstanding_balance||'0'} USD`}/></div><p className="of-muted" style={{marginTop:12}}>Số liệu được tính trực tiếp từ cơ sở dữ liệu, không sử dụng dữ liệu giả.</p></div></div>}</div>
}
function Row({label,value}){return <div style={{display:'flex',justifyContent:'space-between',gap:10,padding:'8px 10px',border:'1px solid #e2e8f0',borderRadius:10,background:'#f8fafc'}}><span className="of-muted">{label}</span><strong>{typeof value==='number'?value.toLocaleString('vi-VN'):value}</strong></div>}
